##########################
## Alpine based Terraform with Bash and GIT ##
##########################
FROM hashicorp/terraform
LABEL maintainer hkolli

RUN apk --update --no-cache add bash 

ENTRYPOINT  ["/bin/bash"]
